# Generated by Django 3.0.4 on 2020-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=43.238949, max_digits=17, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=76.889709, max_digits=17, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
