# Generated by Django 3.0.3 on 2020-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200309_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='content',
            field=models.CharField(editable=False, max_length=255, verbose_name='Content'),
        ),
    ]
