# Generated by Django 3.0.4 on 2020-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, verbose_name='Longitude'),
        ),
    ]
