# Generated by Django 3.0.3 on 2020-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200309_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Verification code'),
        ),
    ]
