# Generated by Django 3.0.3 on 2020-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200310_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
