# Generated by Django 3.0.3 on 2020-03-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=256, verbose_name='Event title')),
                ('description', models.CharField(max_length=1024, verbose_name='Brief description')),
                ('start', models.DateTimeField(verbose_name='Event begining')),
                ('end', models.DateTimeField(verbose_name='Event ending')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Location')),
            ],
        ),
    ]
