# Generated by Django 3.0.2 on 2020-02-27 03:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='e_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_brief_description',
            field=models.CharField(default='', max_length=64, verbose_name='Brief description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date and time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_state',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Moderating'), (4, 'Archived')], default=1, verbose_name='Event state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Charity'), (2, 'Party'), (3, 'Exhibition'), (4, 'Concert'), (5, 'Movie'), (6, 'Theatre'), (7, 'Meeting'), (8, 'Education'), (9, 'Business'), (10, 'Entertainment'), (11, 'Children'), (12, 'Other')], default=3, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Event user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=32, verbose_name='Event title'),
        ),
    ]
