# Generated by Django 3.0.4 on 2020-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200503_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(max_length=20, verbose_name='Price'),
        ),
    ]
