# Generated by Django 3.0.3 on 2020-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200318_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude'),
        ),
    ]
