# Generated by Django 3.0.3 on 2020-03-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200318_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cateories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
