# Generated by Django 3.0.4 on 2020-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_category_favorite_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='telegram_chat',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
